name: Leak Check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install clang
      run: |
        sudo apt-get update
        sudo apt-get install -y clang
    - name: Fetch prebuilt libv8
      run: go run scripts/fetch-libv8.go
    - name: Go Test
      env:
        CC: clang
        CXX: clang++
        CGO_CXXFLAGS: "-Wno-comment -Wno-vla-cxx-extension"
      run: |
        go test -c --tags leakcheck
        ./v8go.test
